// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvata: typeof import('anu-vue')['AAvata']
    AAvatar: typeof import('anu-vue')['AAvatar']
    ABtn: typeof import('anu-vue')['ABtn']
    ACard: typeof import('anu-vue')['ACard']
    AInput: typeof import('anu-vue')['AInput']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
