// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('anu-vue')['AAvatar']
    ABtn: typeof import('anu-vue')['ABtn']
    ACard: typeof import('anu-vue')['ACard']
    ACheckbox: typeof import('anu-vue')['ACheckbox']
    AChip: typeof import('anu-vue')['AChip']
    AddItem: typeof import('./src/components/AddItem.vue')['default']
    AddProductScreen: typeof import('./src/components/AddProductScreen.vue')['default']
    ADialog: typeof import('anu-vue')['ADialog']
    AInput: typeof import('anu-vue')['AInput']
    ASelect: typeof import('anu-vue')['ASelect']
    CardItem: typeof import('./src/components/CardItem.vue')['default']
    EventScreen: typeof import('./src/components/EventScreen.vue')['default']
    InventoryCard: typeof import('./src/components/InventoryCard.vue')['default']
    InventoryTable: typeof import('./src/components/InventoryTable.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}
